const fs = require('node:fs');
const path = require('node:path');
const { createHash } = require('node:crypto');
const root = process.argv[2];
if (!root) throw new Error('missing root');
const inputPath = path.join(root, 'apps/api/src/index.ts');
const before = fs.readFileSync(inputPath, 'utf8');
const gitHash = s => createHash('sha1').update(`blob ${Buffer.byteLength(s)}\0`).update(s).digest('hex');
if (gitHash(before) !== '76f6a31170834ab6de2fd961e51ce93bfa49391d') throw new Error('baseline_index_hash_mismatch');
const start = before.indexOf('function validateMediaDimensions(');
const end = before.indexOf('function normalizeDocumentFilename(', start);
if (start < 0 || end < start) throw new Error('invalid_extraction_boundaries');
const block = before.slice(start, end);
const moduleContent = 'import type { RoomDocumentMetadata } from "./storage.js";\nimport type { MultipartPart } from "./multipart-form-data.js";\n\n' + block.replace(/^function (inspectImageDocument|inspectVideoDocument)\(/gm, 'export function $1(').replace(/\n\n$/, '\n');
const importLine = 'import { inspectImageDocument, inspectVideoDocument } from "./document-media-metadata.js";\n\n';
const anchor = 'import { noteExportFilename, noteExportJson, formatNoteMarkdown, formatRoomNotesMarkdown } from "./notes-export.js";\n\n';
if (before.split(anchor).length !== 2) throw new Error('ambiguous_import_anchor');
const after = (before.slice(0, start) + before.slice(end)).replace(anchor, anchor + importLine);
const reconstructed = after.replace(importLine, '').replace('function normalizeDocumentFilename(', block + 'function normalizeDocumentFilename(');
if (reconstructed !== before) throw new Error('reconstruction_mismatch');
fs.writeFileSync(inputPath, after);
fs.writeFileSync(path.join(root, 'apps/api/src/document-media-metadata.ts'), moduleContent);
const summary = {base: '33a519a470d24f21d1be78fcb72ccc81d774ec84', beforeLines: before.split('\n').length - 1, afterLines: after.split('\n').length - 1, beforeHash: gitHash(before), afterHash: gitHash(after), moduleHash: gitHash(moduleContent), byteExactReconstruction: true};
fs.writeFileSync(path.join(root, 'extraction.json'), JSON.stringify(summary, null, 2)+'\n');
console.log(JSON.stringify(summary));
