import { randomUUID } from "node:crypto";
import { test, expect } from "playwright/test";
import type { AuthorHttpPackage, AuthorHttpSession } from "../../apps/api/src/plugins/author-http.test-helper.js";
import { assertDenied, assertPublicDto, bearer, browserContent, createExternalAuthorProject, downloadPublicSdk,
  inviteTokenFromLink, nativeMarker, pluginPath, privateHttp, sha256, startIsolatedAuthorApi, type ExternalArtifact } from "./plugin-author-scenarios";

// Override CI's retained-on-failure trace too: private invitations, RS2, source and
// arbitrary flat config may only live in memory/the cleaned external author project.
test.use({ trace: "off", screenshot: "off", video: "off" });

test("T05 isolated v2 API author installs external CLI artifacts; admitted browsers receive only exact bound bytes", async ({ page, request }) => {
  test.setTimeout(240_000);
  const api = await startIsolatedAuthorApi();
  let author: Awaited<ReturnType<typeof createExternalAuthorProject>> | undefined;
  try {
    // SDK download comes from the wrapper's current local public server, not a
    // copied workspace package or an SDK pack generated by this test.
    author = await createExternalAuthorProject(await downloadPublicSdk(request));
    const first = await author.build(`external.greeting-${randomUUID().replaceAll("-", "")}`);
    const second = await author.build(`external.other-${randomUUID().replaceAll("-", "")}`);
    const tenantId = `plugin-author-${randomUUID()}`;
    expect((await privateHttp(api.base, "/api/tenants", "POST", api.adminHeaders, { tenantId, name: "Isolated plugin author" })).status).toBe(201);
    const created = await privateHttp(api.base, "/api/rooms", "POST", api.adminHeaders, {
      tenantId, templateId: "meeting-room-basic", name: "Private external author API", visibility: "private", guestAllowed: true,
      features: { voice: false, screenShare: false, spatialAudio: false }
    });
    expect(created.status).toBe(201);
    const roomId = created.json<{ roomId: string }>().roomId;
    // Genuine private HTTP invitations and token admission; admin only provisions
    // the room/invitations and never installs/binds packages in this scenario.
    async function session(role: string) {
      const invitation = await privateHttp(api.base, `/api/rooms/${roomId}/invites`, "POST", api.adminHeaders,
        { role, waitingRoomEnabled: false, expiresInSeconds: 600 });
      expect(invitation.status).toBe(201);
      const inviteToken = inviteTokenFromLink(invitation.json<{ inviteLink: string }>().inviteLink);
      const admitted = await privateHttp(api.base, "/api/tokens/state", "POST", {},
        { identityProtocolVersion: 2, roomId, displayName: "External plugin participant", inviteToken });
      expect(admitted.status).toBe(200);
      return { ...admitted.json<AuthorHttpSession>(), inviteToken };
    }
    const host = await session("host");
    const member = await session("member");
    const guest = await session("guest");
    for (const [session, role] of [[host, "host"], [member, "member"], [guest, "guest"]] as const) {
      expect(session.token.startsWith("rs2.")).toBe(true);
      expect(session.role === role).toBe(true);
    }
    const privateValues = [api.localRoot, host.token, host.identityCredential, host.inviteToken,
      member.token, member.identityCredential, guest.token, guest.identityCredential];
    const call = (suffix: string, method = "GET", body?: unknown, actor = host) =>
      privateHttp(api.base, pluginPath(roomId, suffix), method, bearer(actor.token), body);
    const readLibrary = async () => {
      const response = await call("packages"); expect(response.status).toBe(200);
      const dto = response.json<{ revision: number; packages: AuthorHttpPackage[]; bindings: Array<Record<string, unknown>> }>();
      assertPublicDto(dto, privateValues); return dto;
    };
    const contentPath = (value: AuthorHttpPackage) => `packages/${value.packageId}/content`;
    const greeting = "PRIVATE_AUTHOR_CONFIG_<script>must remain data</script>";
    const changedGreeting = "PRIVATE_AUTHOR_CONFIG_UPDATED";
    const binding = (value: AuthorHttpPackage, expectedRevision: number, config = greeting, enabled = true) => ({
      expectedRevision, packageId: value.packageId, version: value.version, artifactSha256: value.artifactSha256,
      enabled, config: { greeting: config }, approvedCapabilities: [...value.manifest.requestedCapabilities]
    });
    async function upload(artifact: ExternalArtifact) {
      const response = await call("packages", "POST", artifact.bytes); expect(response.status).toBe(201);
      const dto = response.json<{ package: AuthorHttpPackage }>(); assertPublicDto(dto, privateValues);
      const value = dto.package;
      expect(value.pluginId === artifact.pluginId && value.version === artifact.version).toBe(true);
      expect(value.artifactSha256).toBe(artifact.artifactSha256);
      expect(value.manifest.entrySha256).toBe(artifact.entrySha256);
      expect(value.byteLength).toBe(artifact.bytes.byteLength);
      expect(value.state === "ready" && value.uploadSettled).toBe(true);
      expect(JSON.stringify(value.manifest.requestedCapabilities) === JSON.stringify(artifact.capabilities)).toBe(true);
      expect(Object.keys(value.manifest.configSchema).join() === "greeting").toBe(true);
      return value;
    }
    async function runtime(actor: AuthorHttpSession) {
      const response = await privateHttp(api.base, pluginPath(roomId, "runtime"), "GET", bearer(actor.token));
      expect(response.status).toBe(200);
      const dto = response.json<{ revision: number; bindings: Array<Record<string, unknown>> }>(); assertPublicDto(dto, privateValues); return dto;
    }
    async function assertRevision(response: Awaited<ReturnType<typeof call>>, revision: number) {
      expect(response.status).toBe(200); const dto = response.json<{ ok: boolean; revision: number }>();
      assertPublicDto(dto, privateValues); expect(dto.ok).toBe(true); expect(dto.revision).toBe(revision);
    }

    const empty = await readLibrary(); expect(empty.revision).toBe(0); expect(empty.packages.length + empty.bindings.length).toBe(0);
    const value = await upload(first);
    // Upload alone never grants source access, even to its admitted Host.
    assertDenied(await call(contentPath(value)), 403, "plugin_content_not_bound");
    assertDenied(await call(`bindings/${value.pluginId}`, "PUT", { ...binding(value, 0), version: "1.0.9" }), 400, "plugin_invalid_binding");
    const wrongHash = `${value.artifactSha256[0] === "0" ? "1" : "0"}${value.artifactSha256.slice(1)}`;
    assertDenied(await call(`bindings/${value.pluginId}`, "PUT", { ...binding(value, 0), artifactSha256: wrongHash }), 400, "plugin_invalid_binding");
    assertDenied(await call(`bindings/${value.pluginId}`, "PUT", { ...binding(value, 0),
      storageKey: "room-plugins/caller-selected", backendFingerprint: "a".repeat(64) }), 400, "plugin_invalid_binding");
    expect((await readLibrary()).revision).toBe(0);
    await assertRevision(await call(`bindings/${value.pluginId}`, "PUT", binding(value, 0)), 1);
    const other = await upload(second);
    await assertRevision(await call(`bindings/${other.pluginId}`, "PUT", binding(other, 1)), 2);
    let library = await readLibrary(); expect(library.revision).toBe(2); expect(library.packages.length).toBe(2); expect(library.bindings.length).toBe(2);
    expect(library.bindings.every(row => JSON.stringify(row.config) === JSON.stringify({ greeting }) &&
      JSON.stringify(row.approvedCapabilities) === JSON.stringify(["status.set"]))).toBe(true);
    // Public DTO projection is also checked against actual private storage values,
    // without serializing raw records into assertions or Playwright attachments.
    const rows = (await api.pool.query("select storage_key,backend_fingerprint from room_plugin_packages where room_id=$1", [roomId])).rows;
    assertPublicDto(library, [...privateValues, ...rows.flatMap(row => [row.storage_key, row.backend_fingerprint])]);

    const navigation = await page.goto(`${api.base}/rooms/${roomId}`, { waitUntil: "domcontentloaded" }).catch(() => { throw new Error("plugin_author_room_shell_navigation_failed"); });
    expect(navigation?.status()).toBe(200);
    for (const actor of [member, guest]) {
      const snapshot = await runtime(actor); expect(snapshot.revision).toBe(2); expect(snapshot.bindings.length).toBe(2);
      for (const saved of [value, other]) {
        const current = snapshot.bindings.find(row => row.pluginId === saved.pluginId)!;
        expect(Boolean(current)).toBe(true);
        expect(current.packageId === saved.packageId && current.version === saved.version && current.artifactSha256 === saved.artifactSha256).toBe(true);
        expect(current.contentUrl === pluginPath(roomId, contentPath(saved))).toBe(true);
        const downloaded = await browserContent(page, pluginPath(roomId, contentPath(saved)), actor.token);
        expect(downloaded.status).toBe(200); expect(downloaded.artifactSha256).toBe(saved.artifactSha256);
        expect(downloaded.declaredSha256).toBe(saved.artifactSha256); expect(downloaded.nativeExecuted).toBe(false);
        const raw = await call(contentPath(saved), "GET", undefined, actor);
        expect(raw.status).toBe(200); expect(raw.bytes.equals(saved.packageId === value.packageId ? first.bytes : second.bytes)).toBe(true);
        expect(sha256(raw.bytes)).toBe(saved.artifactSha256);
        expect(raw.headers["content-type"] === "application/octet-stream" && raw.headers["x-content-type-options"] === "nosniff").toBe(true);
        expect(raw.headers["cache-control"] === "no-store" && raw.headers["content-security-policy"].startsWith("sandbox;")).toBe(true);
      }
      for (const [suffix, method, body] of [["packages", "GET", undefined], ["packages", "POST", first.bytes],
        [`bindings/${value.pluginId}`, "PUT", binding(value, 2)], [`bindings/${value.pluginId}`, "DELETE", { expectedRevision: 2 }],
        [`packages/${value.packageId}`, "DELETE", undefined]] as const) {
        assertDenied(await call(suffix, method, body, actor), 403, "plugin_author_forbidden");
      }
    }
    for (const suffix of ["runtime", contentPath(value)]) {
      assertDenied(await privateHttp(api.base, pluginPath(roomId, suffix), "GET", api.adminHeaders), 401, "identity_required");
    }
    expect((await readLibrary()).revision).toBe(2);

    await assertRevision(await call(`bindings/${value.pluginId}`, "PUT", binding(value, 2, changedGreeting)), 3);
    assertDenied(await call(`bindings/${value.pluginId}`, "PUT", binding(value, 2)), 409, "plugin_revision_conflict");
    library = await readLibrary(); expect(library.revision).toBe(3);
    expect(JSON.stringify(library.bindings.find(row => row.pluginId === value.pluginId)?.config) === JSON.stringify({ greeting: changedGreeting })).toBe(true);
    expect(JSON.stringify((await runtime(member)).bindings.find(row => row.pluginId === value.pluginId)?.config) === JSON.stringify({ greeting: changedGreeting })).toBe(true);

    // A version update that asks for more capabilities needs approval tied to its
    // precise new hash; an old artifact's approval cannot authorize it.
    const nextArtifact = await author.build(first.pluginId, "1.0.1", ["status.set", "seating.cancelPendingOwnClaim"]);
    const next = await upload(nextArtifact);
    const update = binding(next, 3, changedGreeting);
    assertDenied(await call(`bindings/${value.pluginId}`, "PUT", update), 403, "plugin_capability_approval_required");
    assertDenied(await call(`bindings/${value.pluginId}`, "PUT", { ...update,
      capabilityApproval: { artifactSha256: value.artifactSha256, capabilities: update.approvedCapabilities } }), 403, "plugin_capability_approval_required");
    await assertRevision(await call(`bindings/${value.pluginId}`, "PUT", { ...update,
      capabilityApproval: { artifactSha256: next.artifactSha256, capabilities: update.approvedCapabilities } }), 4);
    assertDenied(await call(contentPath(value), "GET", undefined, member), 403, "plugin_content_not_bound");
    const newBytes = await browserContent(page, pluginPath(roomId, contentPath(next)), guest.token);
    expect(newBytes.status).toBe(200); expect(newBytes.artifactSha256).toBe(next.artifactSha256); expect(newBytes.nativeExecuted).toBe(false);
    expect((await runtime(member)).bindings.find(row => row.pluginId === next.pluginId)?.artifactSha256).toBe(next.artifactSha256);

    await assertRevision(await call(`bindings/${next.pluginId}`, "PUT", binding(next, 4, changedGreeting, false)), 5);
    expect((await runtime(guest)).bindings.length).toBe(1);
    for (const actor of [host, member, guest]) assertDenied(await call(contentPath(next), "GET", undefined, actor), 403, "plugin_content_not_bound");
    assertDenied(await call(`packages/${next.packageId}`, "DELETE"), 409, "plugin_package_bound");
    await assertRevision(await call(`bindings/${next.pluginId}`, "DELETE", { expectedRevision: 5 }), 6);
    await assertRevision(await call(`bindings/${other.pluginId}`, "DELETE", { expectedRevision: 6 }), 7);
    for (const saved of [value, next, other]) {
      assertDenied(await call(contentPath(saved), "GET", undefined, guest), 403, "plugin_content_not_bound");
      expect((await call(`packages/${saved.packageId}`, "DELETE")).status).toBe(200);
    }
    library = await readLibrary(); expect(library.revision).toBe(7); expect(library.packages.length).toBe(0); expect(library.bindings.length).toBe(0);
    expect((await runtime(member)).bindings.length).toBe(0);
    expect(Object.keys(await api.files()).length).toBe(0);
    await author.assertNotExecuted();
    expect(await page.evaluate(marker => Reflect.has(globalThis, marker), nativeMarker)).toBe(false);
    // No full-suite or shared staging activation claim: this is the isolated
    // WM05–06 API step. T01a remains required before activating author routes.
  } finally {
    await page.goto("about:blank").catch(() => undefined);
    try { await api.close(); } finally { await author?.close(); }
  }
});
