import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(path.join(process.cwd(),'package.json'));
const ts=require('typescript');
const filename='apps/runtime-web/src/main.ts';
const line='import { createMediaObjectTestControls } from "./testing/media-object-test-controls.js";\n';
let text=fs.readFileSync(filename,'utf8');
assert.ok(text.startsWith(line));
text=text.slice(line.length);
const anchor='import { createSeatMarkerViewController } from "./interaction/seat-marker-view.js";\n';
assert.equal(text.split(anchor).length,2);
text=text.replace(anchor,anchor+line);
const imports=source=>ts.createSourceFile('main.ts',source,ts.ScriptTarget.Latest,true).statements.filter(ts.isImportDeclaration).map(node=>node.moduleSpecifier.text);
const before=imports(fs.readFileSync(path.join(process.env.EVIDENCE,'main-baseline.ts'),'utf8'));
assert.deepEqual(imports(text),[...before,'./testing/media-object-test-controls.js']);
fs.writeFileSync(filename,text);
console.log('Original import evaluation order preserved; side-effect-free test factory import added last.');
